### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/project-addons#10]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] project_claims
- [ ] project_events
- [ ] project_events_copy
- [ ] project_events_operations
- [ ] project_fix_price
- [ ] project_issue_ext
- [ ] project_partner_event_registration
- [ ] project_report
- [ ] project_task_deadline_visible
- [ ] project_task_ending
- [ ] project_task_generated_with_product_performance
- [ ] project_task_merge
- [ ] project_task_tag
- [ ] project_task_work_estimated_time
- [ ] project_user_product
- [ ] task_delegation_wizard
