### ISSUE TITLE
Migration to version 12.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/project-addons#161]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

# Modules to migrate

- [ ] project_billing_plan
- [ ] project_budget
- [ ] project_budget_characterization
- [ ] project_characterization
- [ ] project_characterization_rol
- [ ] project_close_info
- [ ] project_diary
- [ ] project_extension_building
- [ ] project_funding
- [ ] project_goal
- [ ] project_idea
- [ ] project_partner_rol
- [ ] project_phase
- [ ] project_phase_version
- [ ] project_picking_shortcut
- [ ] project_purchase_utilities
- [ ] project_risk
- [ ] project_task_cost
- [ ] project_task_milestone
- [ ] project_task_milestone_billing_plan
- [ ] project_task_skill
- [ ] project_team
- [ ] project_team_partner_rol
- [ ] project_technical
- [ ] project_utilities
- [ ] project_version
- [ ] project_viability
