### ISSUE TITLE
Migration to version 13.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/project-addons#218]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

# Modules to migrate

- [ ] project_billing_plan
- [ ] project_phase
- [ ] project_purchase_utilities
- [ ] project_task_milestone
- [ ] project_task_milestone_billing_plan

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
