### ISSUE TITLE
Migration to version 15.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/project-addons#253]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

# Modules to migrate

- [ ] project_task_meeting
- [ ] project_task_milestone
- [ ] project_task_service_partner
- [ ] project_vehicle

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
